project:
  type: website

website:
  page-navigation: true
  title: "Junchuan Yu"
  site-url: "https://junchuanyu.netlify.app/teaching/"
  google-analytics: "G-2J79YYG9CZ"
  page-footer:
    left: "Blog made with [Quarto](https://quarto.org/), by Junchuan Yu. "
    right:
      - icon: envelope
        href: jason.yu.mail@qq.com
      - icon: github
        href: https://github.com/JunchuanYu
      - icon: book
        href: https://www.zhihu.com/people/yu-jun-chuan-84
      - icon: bootstrap
        href: https://space.bilibili.com/18814004/

  navbar:
    right:
      - text: About
        href: about.qmd
      - text: Posts
        href: posts/index.qmd
      - text: Publications
        href: publication/index.qmd
      - text: Talks
        href: talks/index.qmd
      - text: Teaching
        href: teaching/index.qmd
      - icon: github
        href: https://github.com/JunchuanYu
      - icon: book
        href: https://www.zhihu.com/people/yu-jun-chuan-84
      - icon: bootstrap
        href: https://space.bilibili.com/18814004/

format:
  html:
    smooth-scroll: true
    theme: journal
    css: styles.css
    link-external-icon: false
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.junchuanyu\.com\/**'
    citations-hover: true
    footnotes-hover: true
    include-in-header: meta.html
    toc: true
    code-link: true

editor: visual

comments:
  giscus:
    repo: JunchuanYu/blog-en
